[package]
name = "muldiv"
version = "0.1.0"
authors = ["Sebastian DrÃ¶ge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/rust-muldiv"
license = "LGPL-2.1+"

[features]
default = []
x86-64-assembly = []

[dependencies]

[dev-dependencies]
num = { version = "0.1.*" }
rand = { version = "0.3.*" }
